### ISSUE TITLE
Passbolt Browser Extension Regularly Queries Unexpected Port 65080

### ISSUE THREAD

**Issue by frederik-hoeft** [passbolt/passbolt_browser_extension#230]
## Description

During a review of our internal firewall logs, we noticed an elevated number of blocked requests from an internal end-user device to the docker host that is running a Passbolt CE container instance. After some investigation and further network traffic analysis, we were able to pinpoint the source of these requests to the Passbolt browser extension. The extension is making requests to port `65080`, which does not match the configured default HTTPS port (`443`). We have searched all relevant configuration files and found no reference to port `65080` being assigned as part of our server configuration. Port `65080` is also never mentioned in any of the [Docker configuration manuals](https://www.passbolt.com/docs/hosting/install/ce/docker/).

## Observed Behavior

The Brave (Chrome) browser extension is making attempts to connect to the following URI:

```
https://10.X.X.X:65080/auth/is-authenticated.json?api-version=v2
```

where `10.X.X.X` is the (redacted) IP address of the docker host running the Passbolt container instance, and `65080` is the incorrect port. 

Taking a look at the source code, these requests seem to originates from here: https://github.com/passbolt/passbolt_browser_extension/blob/3a276a44d0ea16211d45a366aca8fc7537fa06d4/src/all/background_page/service/authenticationStatusService.js#L30

On a peculiar side note, these requests don't seem to attempt to connect to the host through the assigned network-local domain name (referred to as `[INTERNAL_DOMAIN]` in the following), but rather directly to the IP address. Although this could just be the representation of the request URLs in the Chrome network traffic inspector.

Even though these requests are ultimately blocked, we have no reports from our end-users of functionality of the Passbolt browser extension being affected. This issue is more of a nuisance and a potential security concern, as it clutters our firewall logs and could potentially hide more serious issues.

## Expected Behavior

The Passbolt browser extension should be making requests to `/auth/is-authenticated.json?api-version=v2` through the expected default HTTPS port (`443`) as seems to be done for all other requests made by the extension.

## Additional Information

The Passbolt web UI works correctly when accessed through `https://[INTERNAL_DOMAIN]` and the browser extension seems to work correctly too, except that it makes these blocked background requests to port `65080` from time to time. This behavior persists across multiple reboots and browser sessions. We only store firewall logs for a few months, so we are unable to determine when exactly this behavior started. The relevant troubleshooting information has been included below for reference.

Could you please advise if this is a misconfiguration on our part or a bug in the extension's logic for determining the Passbolt server address?

Thank you!

## Troubleshooting Information

**Browser:** Brave Version 1.75.181 Chromium: 133.0.6943.141 (Official Build) (64-bit)  
**Passbolt Extension:** Version 4.11.0 for Chrome  
**Chrome Network Traffic Logs:** 

```json
...
{"params":{"cors_preflight_policy":"consider_preflight","headers":"sec-ch-ua-platform: \"Windows\"\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36\r\nAccept: application/json\r\nsec-ch-ua: \"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Brave\";v=\"132\"\r\ncontent-type: application/json\r\nsec-ch-ua-mobile: ?0\r\nSec-GPC: 1\r\n\r\n","is_revalidating":false,"method":"GET","url":"https://10.X.X.X:65080/auth/is-authenticated.json?api-version=v2"},"phase":1,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":553},
{"params":{"preflight_required":true,"preflight_required_reason":"disallowed_header"},"phase":0,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":554},
{"params":{"priority":"MEDIUM","traffic_annotation":101845102,"url":"https://10.X.X.X:65080/auth/is-authenticated.json?api-version=v2"},"phase":1,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":2},
{"phase":1,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":124},
{"phase":2,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":124},
{"params":{"get_sts_state_result":false,"host":"10.X.X.X","host_found_in_hsts_bypass_list":false,"should_upgrade_to_ssl":false},"phase":0,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":569},
{"params":{"initiator":"chrome-extension://didegimhafipceonhjepacocaffmoppf","load_flags":147456,"method":"GET","network_isolation_key":"chrome-extension://didegimhafipceonhjepacocaffmoppf chrome-extension://didegimhafipceonhjepacocaffmoppf","request_type":"other","site_for_cookies":"SiteForCookies: {site=chrome-extension://didegimhafipceonhjepacocaffmoppf; schemefully_same=true}","url":"https://10.X.X.X:65080/auth/is-authenticated.json?api-version=v2"},"phase":1,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":120},
{"phase":1,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":574},
{"params":{"cache_filter":"none","frame_entry":"none","top_frame_primary":"none"},"phase":2,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":574},
{"params":{"privacy_mode":"disabled"},"phase":0,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":562},
{"phase":1,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":123},
{"phase":2,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":123},
{"params":{"allow_cached_response":true,"dns_query_type":"UNSPECIFIED","host":"https://10.X.X.X:65080","is_speculative":false,"network_anonymization_key":"chrome-extension://didegimhafipceonhjepacocaffmoppf same_site","secure_dns_policy":0},"phase":1,"source":{"id":2,"start_time":"100415","type":28},"time":"1396717","type":3},
{"params":{"cached":true,"ipv6_available":false},"phase":0,"source":{"id":2,"start_time":"100415","type":28},"time":"1396717","type":4},
{"phase":2,"source":{"id":2,"start_time":"100415","type":28},"time":"1396717","type":3},
{"phase":1,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":138},
{"phase":2,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":138},
{"phase":1,"source":{"id":11164,"start_time":"1396717","type":1},"time":"1396717","type":139},
...
```

**Passbolt Server Docker Compose (redacted)** for reference:

```yaml
services:
  db:
    image: mariadb:10.11
    container_name: "passbolt-mariadb"
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: ${PB_MYSQL_PASSWORD}
    volumes:
      - /[REDACTED]/volumes/passbolt/mysql:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:4.10.1-1-ce-non-root
    container_name: "passbolt"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_DEFAULT_LOCALE: "en_US"
      APP_FULL_BASE_URL: https://[INTERNAL_DOMAIN]
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: ${PB_MYSQL_PASSWORD}
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      EMAIL_DEFAULT_FROM_NAME: "Passbolt"
      EMAIL_DEFAULT_FROM: ${PB_EMAIL_ADDRESS}
      EMAIL_TRANSPORT_DEFAULT_HOST: ${PB_SMTP_HOST}
      EMAIL_TRANSPORT_DEFAULT_PORT: ${PB_SMTP_PORT}
      EMAIL_TRANSPORT_DEFAULT_USERNAME: ${PB_EMAIL_ADDRESS}
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: ${PB_EMAIL_PASSWORD}
      EMAIL_TRANSPORT_DEFAULT_TLS: "true"
      PASSBOLT_SSL_FORCE: "true"
      PASSBOLT_GPG_SERVER_KEY_PUBLIC: "/etc/passbolt/gpg/serverkey.asc"
      PASSBOLT_GPG_SERVER_KEY_PRIVATE: "/etc/passbolt/gpg/serverkey_private.asc"
      PASSBOLT_GPG_SERVER_KEY_FINGERPRINT: ${PB_GPG_FINGERPRINT}
      PASSBOLT_PLUGINS_SELF_REGISTRATION_ENABLED: "false"
    volumes:
      - /[REDACTED]/containers/passbolt/certs/passbolt.crt:/etc/passbolt/certs/certificate.crt:ro
      - /[REDACTED]/containers/passbolt/certs/passbolt.key:/etc/passbolt/certs/certificate.key:ro
      - /[REDACTED]/volumes/passbolt/passbolt/gpg:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - 127.0.0.1:11080:4433

volumes:
  gpg_volume:
  jwt_volume:
```

**nginx Reverse Proxy Configuration (redacted)** for reference:

```conf
#################################################################################
#                                   Passbolt                                    #
#################################################################################
server {
    server_name [INTERNAL_DOMAIN];

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # forward to passbolt container
        proxy_pass https://127.0.0.1:11080;
    }

    listen 10.X.X.X:443 ssl;
    ssl_certificate /etc/ssl/[INTERNAL_DOMAIN]/passbolt.crt;
    ssl_certificate_key /etc/ssl/[INTERNAL_DOMAIN]/passbolt.key;
}

# CNAME --> A
server {
    server_name [INTERNAL_DOMAIN_ALT];
    return 301 https://[INTERNAL_DOMAIN]$request_uri;
    listen 10.X.X.X:443;
}

# http --> https
server {
    server_name [INTERNAL_DOMAIN] [INTERNAL_DOMAIN_ALT];
    return 301 https://$host$request_uri;
    listen 10.X.X.X:80;
}
```
